-- Master student table (identity by No. Kad Pengenalan)
create table if not exists public.nilam_students (
  no_kad_pengenalan text primary key,
  nama_murid text not null,
  jantina text,
  email_google_classroom text,
  kelas_2026 text,
  kelas_2027 text,
  kelas_2028 text,
  kelas_2029 text,
  kelas_2030 text,
  kelas_2031 text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Monthly NILAM records keyed by student IC + year + month
create table if not exists public.nilam_records (
  id bigint generated by default as identity primary key,
  no_kad_pengenalan text not null references public.nilam_students (no_kad_pengenalan) on update cascade,
  tahun text not null default to_char(now(), 'YYYY'),
  bulan text not null,
  bil integer not null check (bil > 0),
  nama text not null,
  kelas text not null,
  bahan_digital integer not null default 0 check (bahan_digital between 0 and 999),
  bahan_bukan_buku integer not null default 0 check (bahan_bukan_buku between 0 and 999),
  fiksyen integer not null default 0 check (fiksyen between 0 and 999),
  bukan_fiksyen integer not null default 0 check (bukan_fiksyen between 0 and 999),
  bahasa_melayu integer not null default 0 check (bahasa_melayu between 0 and 999),
  bahasa_inggeris integer not null default 0 check (bahasa_inggeris between 0 and 999),
  lain_lain_bahasa integer not null default 0 check (lain_lain_bahasa between 0 and 999),
  jumlah_aktiviti integer not null default 0 check (jumlah_aktiviti between 0 and 2997),
  updated_at_client timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tahun, bulan, no_kad_pengenalan)
);

-- Backward-compatible migrations for existing DB
alter table public.nilam_records
add column if not exists tahun text not null default to_char(now(), 'YYYY');

alter table public.nilam_records
add column if not exists no_kad_pengenalan text;

alter table public.nilam_records
drop constraint if exists nilam_records_bulan_kelas_nama_key;

alter table public.nilam_records
drop constraint if exists nilam_records_tahun_bulan_kelas_nama_key;

create unique index if not exists nilam_records_tahun_bulan_no_kad_key
on public.nilam_records (tahun, bulan, no_kad_pengenalan);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'nilam_records_no_kad_fkey'
  ) then
    alter table public.nilam_records
    add constraint nilam_records_no_kad_fkey
    foreign key (no_kad_pengenalan)
    references public.nilam_students (no_kad_pengenalan)
    on update cascade
    not valid;
  end if;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_nilam_records_updated_at on public.nilam_records;
create trigger trg_nilam_records_updated_at
before update on public.nilam_records
for each row execute function public.set_updated_at();

drop trigger if exists trg_nilam_students_updated_at on public.nilam_students;
create trigger trg_nilam_students_updated_at
before update on public.nilam_students
for each row execute function public.set_updated_at();

-- Yearly summary pivot (class + yearly total 2026..2031)
create or replace view public.nilam_student_year_summary as
with agg as (
  select
    no_kad_pengenalan,
    tahun,
    sum(jumlah_aktiviti)::integer as total_aktiviti
  from public.nilam_records
  group by no_kad_pengenalan, tahun
)
select
  s.no_kad_pengenalan,
  s.nama_murid,
  s.kelas_2026,
  s.kelas_2027,
  s.kelas_2028,
  s.kelas_2029,
  s.kelas_2030,
  s.kelas_2031,
  coalesce(max(case when a.tahun = '2026' then a.total_aktiviti end), 0) as jumlah_aktiviti_2026,
  coalesce(max(case when a.tahun = '2027' then a.total_aktiviti end), 0) as jumlah_aktiviti_2027,
  coalesce(max(case when a.tahun = '2028' then a.total_aktiviti end), 0) as jumlah_aktiviti_2028,
  coalesce(max(case when a.tahun = '2029' then a.total_aktiviti end), 0) as jumlah_aktiviti_2029,
  coalesce(max(case when a.tahun = '2030' then a.total_aktiviti end), 0) as jumlah_aktiviti_2030,
  coalesce(max(case when a.tahun = '2031' then a.total_aktiviti end), 0) as jumlah_aktiviti_2031
from public.nilam_students s
left join agg a on a.no_kad_pengenalan = s.no_kad_pengenalan
group by
  s.no_kad_pengenalan,
  s.nama_murid,
  s.kelas_2026,
  s.kelas_2027,
  s.kelas_2028,
  s.kelas_2029,
  s.kelas_2030,
  s.kelas_2031;

alter table public.nilam_records enable row level security;
alter table public.nilam_students enable row level security;

drop policy if exists "allow_insert_update_select_for_anon" on public.nilam_records;
create policy "allow_insert_update_select_for_anon"
on public.nilam_records
for all
to anon
using (true)
with check (true);

drop policy if exists "allow_insert_update_select_for_anon_students" on public.nilam_students;
create policy "allow_insert_update_select_for_anon_students"
on public.nilam_students
for all
to anon
using (true)
with check (true);
