-- Master student table (identity by No. Kad Pengenalan)
create table if not exists public.nilam_students (
  no_kad_pengenalan text primary key,
  nama_murid text not null,
  jantina text,
  email_google_classroom text,
  kelas_2026 text,
  kelas_2027 text,
  kelas_2028 text,
  kelas_2029 text,
  kelas_2030 text,
  kelas_2031 text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- NILAM session records keyed by teacher session + student
create table if not exists public.nilam_records (
  id bigint generated by default as identity primary key,
  no_kad_pengenalan text not null references public.nilam_students (no_kad_pengenalan) on update cascade,
  tahun text not null default to_char(now(), 'YYYY'),
  bulan text not null,
  tarikh date not null default now()::date,
  nama_pengisi text not null default 'Tidak Diketahui',
  guru text not null default 'Nilam',
  bil integer not null check (bil > 0),
  nama text not null,
  kelas text not null,
  bahan_digital integer not null default 0 check (bahan_digital between 0 and 999),
  bahan_bukan_buku integer not null default 0 check (bahan_bukan_buku between 0 and 999),
  fiksyen integer not null default 0 check (fiksyen between 0 and 999),
  bukan_fiksyen integer not null default 0 check (bukan_fiksyen between 0 and 999),
  ains integer not null default 0 check (ains between 0 and 999),
  bahasa_melayu integer not null default 0 check (bahasa_melayu between 0 and 999),
  bahasa_inggeris integer not null default 0 check (bahasa_inggeris between 0 and 999),
  lain_lain_bahasa integer not null default 0 check (lain_lain_bahasa between 0 and 999),
  jumlah_aktiviti integer not null default 0 check (jumlah_aktiviti between 0 and 4995),
  updated_at_client timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tahun, bulan, tarikh, no_kad_pengenalan, nama_pengisi, guru)
);

-- Backward-compatible migrations for existing DB
alter table public.nilam_records
add column if not exists tahun text not null default to_char(now(), 'YYYY');

alter table public.nilam_records
add column if not exists no_kad_pengenalan text;

alter table public.nilam_records
add column if not exists ains integer not null default 0;

alter table public.nilam_records
add column if not exists tarikh date not null default now()::date;

alter table public.nilam_records
add column if not exists nama_pengisi text not null default 'Tidak Diketahui';

alter table public.nilam_records
add column if not exists guru text not null default 'Nilam';

alter table public.nilam_records
drop constraint if exists nilam_records_jumlah_aktiviti_check;

alter table public.nilam_records
drop constraint if exists nilam_records_jumlah_aktiviti_range_check;

alter table public.nilam_records
add constraint nilam_records_jumlah_aktiviti_range_check
check (jumlah_aktiviti between 0 and 4995);

alter table public.nilam_records
drop constraint if exists nilam_records_bulan_kelas_nama_key;

alter table public.nilam_records
drop constraint if exists nilam_records_tahun_bulan_kelas_nama_key;

alter table public.nilam_records
drop constraint if exists nilam_records_tahun_bulan_no_kad_pengenalan_key;

alter table public.nilam_records
drop constraint if exists nilam_records_tahun_bulan_no_kad_key;

drop index if exists public.nilam_records_tahun_bulan_no_kad_key;

create unique index if not exists nilam_records_tahun_bulan_no_kad_key
on public.nilam_records (tahun, bulan, tarikh, no_kad_pengenalan, nama_pengisi, guru);

alter table public.nilam_records
drop constraint if exists nilam_records_guru_check;

alter table public.nilam_records
add constraint nilam_records_guru_check
check (guru in ('Nilam', 'BM', 'BI'));

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'nilam_records_no_kad_fkey'
  ) then
    alter table public.nilam_records
    add constraint nilam_records_no_kad_fkey
    foreign key (no_kad_pengenalan)
    references public.nilam_students (no_kad_pengenalan)
    on update cascade
    not valid;
  end if;
end;
$$;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- Keep nilam_students class columns in sync from monthly records by year
create or replace function public.sync_student_from_nilam_record()
returns trigger
language plpgsql
as $$
declare
  kelas_col text;
begin
  insert into public.nilam_students (no_kad_pengenalan, nama_murid)
  values (new.no_kad_pengenalan, new.nama)
  on conflict (no_kad_pengenalan)
  do update set
    nama_murid = excluded.nama_murid,
    updated_at = now();

  if new.tahun ~ '^\d{4}$' then
    kelas_col := format('kelas_%s', new.tahun);
    if kelas_col = any (array['kelas_2026', 'kelas_2027', 'kelas_2028', 'kelas_2029', 'kelas_2030', 'kelas_2031']) then
      execute format(
        'update public.nilam_students
         set %I = $1, nama_murid = $2, updated_at = now()
         where no_kad_pengenalan = $3',
        kelas_col
      )
      using new.kelas, new.nama, new.no_kad_pengenalan;
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_nilam_records_updated_at on public.nilam_records;
create trigger trg_nilam_records_updated_at
before update on public.nilam_records
for each row execute function public.set_updated_at();

drop trigger if exists trg_nilam_students_updated_at on public.nilam_students;
create trigger trg_nilam_students_updated_at
before update on public.nilam_students
for each row execute function public.set_updated_at();

drop trigger if exists trg_sync_student_from_record on public.nilam_records;
create trigger trg_sync_student_from_record
after insert or update of tahun, kelas, nama, no_kad_pengenalan on public.nilam_records
for each row execute function public.sync_student_from_nilam_record();

-- Backfill kelas_2026..kelas_2031 from existing records (latest class per student per year)
do $$
declare
  y integer;
  col_name text;
begin
  for y in 2026..2031 loop
    col_name := format('kelas_%s', y);
    execute format(
      $fmt$
      with ranked as (
        select distinct on (no_kad_pengenalan)
          no_kad_pengenalan,
          kelas
        from public.nilam_records
        where tahun = %L
          and coalesce(kelas, '') <> ''
        order by
          no_kad_pengenalan,
          coalesce(updated_at_client, updated_at, created_at) desc
      )
      update public.nilam_students s
      set %I = r.kelas,
          updated_at = now()
      from ranked r
      where s.no_kad_pengenalan = r.no_kad_pengenalan
      $fmt$,
      y::text,
      col_name
    );
  end loop;
end;
$$;

-- Yearly summary pivot (class + yearly total 2026..2031)
drop view if exists public.nilam_student_year_summary;
create view public.nilam_student_year_summary as
with agg as (
  select
    no_kad_pengenalan,
    tahun,
    sum(jumlah_aktiviti)::integer as total_bacaan
  from public.nilam_records
  group by no_kad_pengenalan, tahun
)
select
  s.no_kad_pengenalan,
  s.nama_murid,
  s.kelas_2026,
  s.kelas_2027,
  s.kelas_2028,
  s.kelas_2029,
  s.kelas_2030,
  s.kelas_2031,
  coalesce(max(case when a.tahun = '2026' then a.total_bacaan end), 0) as jumlah_bacaan_2026,
  coalesce(max(case when a.tahun = '2027' then a.total_bacaan end), 0) as jumlah_bacaan_2027,
  coalesce(max(case when a.tahun = '2028' then a.total_bacaan end), 0) as jumlah_bacaan_2028,
  coalesce(max(case when a.tahun = '2029' then a.total_bacaan end), 0) as jumlah_bacaan_2029,
  coalesce(max(case when a.tahun = '2030' then a.total_bacaan end), 0) as jumlah_bacaan_2030,
  coalesce(max(case when a.tahun = '2031' then a.total_bacaan end), 0) as jumlah_bacaan_2031
from public.nilam_students s
left join agg a on a.no_kad_pengenalan = s.no_kad_pengenalan
group by
  s.no_kad_pengenalan,
  s.nama_murid,
  s.kelas_2026,
  s.kelas_2027,
  s.kelas_2028,
  s.kelas_2029,
  s.kelas_2030,
  s.kelas_2031;

alter table public.nilam_records enable row level security;
alter table public.nilam_students enable row level security;

grant usage on schema public to anon;
grant select, insert, update, delete on table public.nilam_records to anon;
grant select, insert, update, delete on table public.nilam_students to anon;
grant usage, select on all sequences in schema public to anon;

drop policy if exists "allow_insert_update_select_for_anon" on public.nilam_records;
create policy "allow_insert_update_select_for_anon"
on public.nilam_records
for all
to anon
using (true)
with check (true);

drop policy if exists "allow_insert_update_select_for_anon_students" on public.nilam_students;
create policy "allow_insert_update_select_for_anon_students"
on public.nilam_students
for all
to anon
using (true)
with check (true);
